### PR TITLE
allow binary data parsing

### PR DESCRIPTION
**Pull request by wildart**
Server throws errors when the response message body contains binary data. This PR should fix this problem.

### CODE REVIEW

**Comment by IainNZ** [comment]
I would love to merge this, but I'm not sure if its going to be a breaking change for someone. I don't really know how this really package works, I just merge PRs...

**Comment by wildart** [comment]
Don't worry, this will fix it.

**Comment by IainNZ** [comment]
@wildart would you like to be a maintainer of HttpServer? I don't really feel qualified at all

**Comment by wildart** [comment]
Sure,  I could maintain it. I studied it quite well because my other package heavily reuses internal functionality of this package.

**Pull request merged**
