### PR TITLE
Changed HttpServer.handle signature from f(req, res) to f(req)

### PR DESCRIPTION
**Pull request by JockLawrie**
As per [#74](https://github.com/JuliaWeb/HttpServer.jl/issues/74)

### CODE REVIEW

**Comment by malmaud** [comment]
Seems the tests are failing. Once they pass, this looks good.

**Comment by IainNZ** [comment]
Can a test for the deprecated version be maintained too, until its removed?

Should probably major-bump this

**Comment by JockLawrie** [comment]
Yeah my bad, sorry. Will fix such that the existing tests pass and create a set of corresponding tests for the new API. Hopefully I'll get to this tomorrow, else Thursday.

**Comment by JockLawrie** [comment]
Closing this in favour of a separate PR coming soon.

**Pull request closed without merging**
