### PR TITLE
Buffer writing to socket to handle connection reset between writes

### PR DESCRIPTION
**Pull request by quatrix**
Hi,

I'm using HttpServer under a HAProxy load balancer that's configured to do a http get as a health check, (specifically `option httpchk GET /health`) and everytime it does the check, I get the following error:

```julia
ERROR (unhandled task failure): write: connection reset by peer (ECONNRESET)
 in yieldto(::Task, ::ANY) at ./event.jl:136
 in wait() at ./event.jl:169
 in stream_wait(::Task) at ./stream.jl:44
 in uv_write(::TCPSocket, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:820
 in unsafe_write(::TCPSocket, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:830
 in write(::TCPSocket, ::Array{UInt8,1}) at ./io.jl:175
 in write(::TCPSocket, ::HttpCommon.Response) at /root/.julia/v0.5/HttpServer/src/HttpServer.jl:182
 in (::HttpServer.#on_message_complete#18{HttpServer.Server,HttpServer.Client{TCPSocket},Bool})(::HttpCommon.Request) at /root/.julia/v0.5/HttpServer/src/HttpServer.jl:447
 in on_message_complete(::Ptr{HttpParser.Parser}) at /root/.julia/v0.5/HttpServer/src/RequestParser.jl:113
 in http_parser_execute(::HttpParser.Parser, ::HttpParser.ParserSettings, ::Array{UInt8,1}) at /root/.julia/v0.5/HttpParser/src/HttpParser.jl:115
 in process_client(::HttpServer.Server, ::HttpServer.Client{TCPSocket}, ::Bool) at /root/.julia/v0.5/HttpServer/src/HttpServer.jl:389
 in (::HttpServer.##8#10{HttpServer.Server,Bool})() at ./task.jl:360

```

It seems like HAProxy tries to close the connection as soon as possible, so when attempting to do another write after

```julia
write(io, join(["HTTP/1.1", response.status, HttpCommon.STATUS_CODES[response.status], "\r\n"], " "))
````

HAProxy already closed the connection and thus we get a ECONNRESET.

I replaced all ```write(io,...``` in that function to push the string to a buffer and then write it all in once. another option would be to do a check that the socket didn't close before each write.

This is my first time writing in Julia so please correct me if this is not idiomatic or terribly inefficient.

Thanks

### CODE REVIEW

**Comment by hustf** [comment]
quatrix, thanks for this! It seems this package isn't getting much attention lately.

The ECCONRESETS, however rare, are a pain. A few can be avoided by telling the sockets to close when finished with the last message: push!(response.headers, "Connection" => "close"). That can help depending on the client and the problem.

I'm not sure if this is on the right way to a good fix, but if it has worked for you then that's a strong indication. It's hardly good behaviour from the client I think, if this is the case. The client should at least read the entire message.

This PR will I believe slow down writing because you are allocating a lot of memory.  Writing to the memory is what takes time, basically. Writing to io is a memory allocation, but twice the allocations makes for twice the time. And in this case, perhaps some more. I'm never quite sure because the compiler is so clever. A good test would give the precise answer.

So buffering should be avoided for the response.data at least, which in your problem case is very small but in other cases is huge.

Also, I think writing to an IOBuffer will be faster overall and perhaps even possible to optimize away for the compiler.  So, iob = IOBuffer(). Then write to iob instead of io. Then write iob to io. Then write the data directly to io.

Another approach would be to not write to a buffer at all, but make a function which produce the continuous string. That's often the best way with Julia.

**Comment by quinnj** [comment]
Do note that most active HTTP-related development has moved to [HTTP.jl](https://github.com/JuliaWeb/HTTP.jl); the code from HttpCommon, URIParser, HttpServer, and Requests has been merged together, modernized, and enhanced for more robust performance and error-handling. It'd be great to focus efforts on that package!

**Comment by hustf** [comment]
With all the direct and indirect dependencies, we will hardly be able to get rid of the old system completely. I think it will be a pity if new explorers will be met with a stream of ecconresets and depwarns.

**Comment by quinnj** [comment]
Hopefully "new explorers" can be directed to actively maintained code in HTTP.jl in the first place, thus avoiding these ecconresets and depwarn problems entirely 😃

**Comment by hustf** [comment]
That would likely be the best. Prominent info about the switch in all of the read me. 

So far I think websocket upgrades are missing from http. So it would be great to get support for fixing this.

**Pull request closed without merging**
